language: go
go: "1.13"
services:
  - docker
dist: bionic
jobs:
  include:
    - script: make build
    - script:
      - make provision
      - "skaffold dev --port-forward=true && sleep 60 && make buckets && make run"
