apiVersion: skaffold/v1beta13
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:v1"
  artifacts:
  - image: clay-server
    context: server
  - image: clay-scraper
    context: image
deploy:
  kubectl:
    manifests:
    - kubernetes/clay-server.yaml
    - kubernetes/minio-deployment.yaml
