apiVersion: skaffold/v1beta17
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:v1"
  artifacts:
    - image: openaustralia/clay-server
      docker:
        dockerfile: build/package/Dockerfile
        target: clay-server
    - image: openaustralia/clay-scraper
      docker:
        dockerfile: build/package/Dockerfile
        target: clay-run
deploy:
  kustomize: {}
