apiVersion: skaffold/v1beta13
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:v1"
  artifacts:
    - image: openaustralia/clay-server
      docker:
        dockerfile: build/package/clay-server/Dockerfile
    - image: openaustralia/clay-scraper
      context: build/package/clay-scraper
deploy:
  kustomize: {}
