apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: openaustralia/yinyo-server
      docker:
        dockerfile: build/package/Dockerfile
        target: yinyo-server
    - image: openaustralia/yinyo-scraper
      docker:
        dockerfile: build/package/Dockerfile
        target: yinyo-run
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:v1"
deploy:
  helm:
    releases:
      - name: yinyo
        chartPath: deployments/helm/yinyo
        values:
          # TODO: Rename this
          image: openaustralia/yinyo-server
        # To force the dependencies to be updated: "helm dep build"
        skipBuildDependencies: true
