apiVersion: skaffold/v1beta13
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:v1"
  artifacts:
  - image: openaustralia/clay-server
    context: images/clay-server
  - image: openaustralia/clay-scraper
    context: images/clay-scraper
deploy:
  kustomize: {}
