apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: openaustralia/yinyo-server
      docker:
        dockerfile: build/package/Dockerfile
        target: yinyo-server
    - image: openaustralia/yinyo-scraper
      docker:
        dockerfile: build/package/Dockerfile
        target: yinyo-run
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:v1"
deploy:
  helm:
    releases:
      - name: yinyo
        chartPath: deployments/helm/yinyo
        valuesFiles:
          - deployments/helm/yinyo-dev-values.yaml
        values:
          # TODO: Rename this
          image: openaustralia/yinyo-server
      - name: minio
        remote: true
        chartPath: stable/minio
        version: "~5.0.17"
        valuesFiles:
          - deployments/helm/minio-dev-values.yaml
      - name: redis
        remote: true
        chartPath: bitnami/redis
        version: "~10.5.13"
        valuesFiles:
          - deployments/helm/redis-dev-values.yaml
