apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: openaustralia/yinyo-server
      docker:
        dockerfile: build/package/server/Dockerfile
    - image: openaustralia/yinyo-run
      docker:
        dockerfile: build/package/run/Dockerfile
deploy:
  helm:
    releases:
      - name: yinyo
        chartPath: deployments/helm/yinyo
        valuesFiles:
          - deployments/helm/yinyo-dev-values.yaml
        values:
          image: openaustralia/yinyo-server
          runImage: openaustralia/yinyo-run
      - name: minio
        remote: true
        chartPath: stable/minio
        version: "~5.0.17"
        valuesFiles:
          - deployments/helm/minio-dev-values.yaml
      - name: redis
        remote: true
        chartPath: bitnami/redis
        version: "~10.5.13"
        valuesFiles:
          - deployments/helm/redis-dev-values.yaml
