openapi: 3.0.1
info:
  title: Yinyo
  description: |
    A wonderfully simple API driven service to reliably execute many long running scrapers in a super scaleable way
  version: "1.0"
servers:
  # TODO: This should change as soon as there is publically available production instance of the API
  # This is currently pointing to a local development server
  - url: http://localhost:8080
tags:
  - name: Core
    description: The minimum you'll need to use
  - name: Optional
    description: Get access to more information about runs
paths:
  /runs:
    summary: Create run
    post:
      tags: ["Core"]
      summary: Create run
      description: |
        Returns with the "run name" which uniquely identifies this run and the "run token" which is a secret to ensure that only you can access the run from here on in. You will need these values to subsequently start, track and access this run.

        You can optionally provide a suggested "name prefix" which will be put at the beginning of the unique name for the run. This is only useful to give more human meaningful names to the runs if that's important in your application. However, you can not depend on the prefix being used exactly as you provide it as some characters are not possible in run names.
      parameters:
        - name: name_prefix
          description: Prefix used when generating run names
          in: query
          schema:
            type: string
      responses:
        200:
          description: Created successfully
          content:
            "application/json":
              schema:
                type: object
                properties:
                  run_name:
                    type: string
                    description: |
                      Uniquely identifies this run. Needed for any subsequent API calls for this run.
                  run_token:
                    type: string
                    description: |
                      Secret value needed to access the run
              example:
                run_name: run-lvg44
                run_token: bMMT7MnU2QbFZbk0lkut401D4uFScUI2
  /runs/{name}/app:
    put:
      tags: ["Core"]
      summary: Upload the code to be run and any local data
      parameters:
        - $ref: "#/components/parameters/name"
      requestBody:
        content:
          application/gzip:
            schema:
              type: string
              description: |
                Directory with code, configuration and data to run. Everything needs to be tarred and gzip compressed.
              format: binary
        required: true
      security:
        - run_token: []
      responses:
        200:
          description: Success
        403:
          $ref: "#/components/responses/bad_auth"
  /runs/{name}/cache:
    summary: Manage build cache
    put:
      tags: ["Optional"]
      summary: Upload a build cache
      parameters:
        - $ref: "#/components/parameters/name"
      requestBody:
        content:
          application/gzip:
            schema:
              description: Build cache exactly as it was downloaded before
              type: string
              format: binary
        required: true
      security:
        - run_token: []
      responses:
        200:
          description: Success
        403:
          $ref: "#/components/responses/bad_auth"
    get:
      tags: ["Optional"]
      summary: Download a build cache
      parameters:
        - $ref: "#/components/parameters/name"
      security:
        - run_token: []
      responses:
        200:
          content:
            application/gzip:
              schema:
                description: Build cache
                type: string
                format: binary
          description: Success
        403:
          $ref: "#/components/responses/bad_auth"
        404:
          description: The build cache doesn't yet exist

  /runs/{name}/start:
    post:
      tags: ["Core"]
      summary: Start the run
      parameters:
        - $ref: "#/components/parameters/name"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                output:
                  type: string
                  description: |
                    Optional relative path (from the directory of the code for the run) to file you want access to later. This will usually be the output of the run.
                env:
                  type: array
                  description: |
                    Optionally set environment variables for the run.
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        description: |
                          Name of the environment variable
                      value:
                        type: string
                        description: |
                          Value of the environment variable
                callback:
                  type: string
                  format: uri
                  description: |
                    Optionally provide a callback URL. For every event a POST to the URL will be made. To be able to authenticate the callback you'll need to specify a secret in the URL. Something like http://my-url-endpoint.com?key=special-secret-stuff would do the trick
            example:
              output: my_output.txt
              env:
                - name: MY_ENVIRONMENT_VARIABLE
                  value: foo
              callback: http://my-url-endpoint.com?key=special-secret-stuff

      security:
        - run_token: []
      responses:
        200:
          description: Success
        400:
          $ref: "#/components/responses/bad_request"
          description: There was a problem with your request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: JSON in body not correctly formatted
        403:
          $ref: "#/components/responses/bad_auth"
      callbacks:
        events:
          "{$request.body#/callback}":
            post:
              requestBody:
                $ref: "#/components/responses/Event"
              responses:
                "200":
                  description: callback successfully processed
  /runs/{name}/events:
    get:
      tags: ["Optional"]
      summary: Attach to run events stream
      description: |
        Watch what is happening to a run in real-time as it gets built and runs. By default this will stream all events that have occurred from the very beginning until now and then as new events occur stream those in real-time.
      parameters:
        - $ref: "#/components/parameters/name"
        - name: last-id
          description: Restart stream immediately after the event with the given ID
          in: query
          schema:
            type: string

      security:
        - run_token: []
      responses:
        200:
          description: Succesfully attached to stream
          content:
            "application/ld+json":
              schema:
                oneOf:
                  - $ref: "#/components/schemas/LogEvent"
                  - $ref: "#/components/schemas/StartEvent"
                  - $ref: "#/components/schemas/FinishEvent"
                  - $ref: "#/components/schemas/LastEvent"
                discriminator:
                  propertyName: type
              example:
                id: "123"
                time: "2019-12-17T03:45:00Z"
                type: log
                data:
                  stage: "build"
                  stream: "stdout"
                  text: "Hello!"
        403:
          $ref: "#/components/responses/bad_auth"
  /runs/{name}/exit-data:
    get:
      tags: ["Optional"]
      summary: Get exit code and usage metrics
      description: |
        Usually at the end of a run you want to know whether the scraper ran succesfully or not. Also returns information about how much resources the run took.
      parameters:
        - $ref: "#/components/parameters/name"
      security:
        - run_token: []
      responses:
        200:
          description: Success
          content:
            "application/json":
              schema:
                type: array
                items:
                  type: object
                  properties:
                    exit_code:
                      type: integer
                    usage:
                      type: object
                      properties:
                        build:
                          $ref: "#/components/schemas/ResourceUsage"
                        run:
                          $ref: "#/components/schemas/ResourceUsage"
        403:
          $ref: "#/components/responses/bad_auth"

  /runs/{name}/output:
    get:
      tags: ["Optional"]
      summary: Get output file
      description: |
        Usually at the end of the scraper run you want to grab the contents of a file which is probably the result of scraping. This allows you to do that. The path to the file needs to be given when the run is started.
      parameters:
        - $ref: "#/components/parameters/name"
      security:
        - run_token: []
      responses:
        200:
          description: Success
          content:
            "application/octet-stream":
              schema:
                type: string
                format: binary
        403:
          $ref: "#/components/responses/bad_auth"
  /runs/{name}:
    delete:
      tags: ["Core"]
      summary: Finalise scraper run
      description: |
        This does final clean up of everything associated with a run. Make sure you always do this as the last API call for a run. After doing this it's not possible to get any more information about this run.
      parameters:
        - $ref: "#/components/parameters/name"
      security:
        - run_token: []
      responses:
        200:
          description: Success
        403:
          $ref: "#/components/responses/bad_auth"
components:
  parameters:
    name:
      name: name
      in: path
      description: The run name (as returned by creating a run)
      required: true
      schema:
        type: string
  responses:
    bad_auth:
      description: The run token was incorrect
    bad_request:
      description: There was a problem with your request
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
          example:
            error: JSON in body not correctly formatted
    Event:
      description: Event - can be one of LogEvent, StartEvent, FinishEvent or LastEvent
      content:
        application/json:
          schema:
            oneOf:
              - $ref: "#/components/schemas/LogEvent"
              - $ref: "#/components/schemas/StartEvent"
              - $ref: "#/components/schemas/FinishEvent"
              - $ref: "#/components/schemas/LastEvent"
            discriminator:
              propertyName: type
          example:
            id: "123"
            time: "2019-12-17T03:45:00Z"
            type: log
            data:
              stage: "build"
              stream: "stdout"
              text: "Hello!"

  schemas:
    Stage:
      type: string
      description: The stage of the life-cycle of the run
      enum:
        - build
        - run
    ResourceUsage:
      type: object
      properties:
        wall_time:
          type: number
          description: Wall clock
        cpu_time:
          type: number
          description: |
            This is the total number of seconds spent executing by the CPU.
            It's the sum of time spent in user and kernel mode.
        max_rss:
          type: integer
          description: |
            This is the maximum resident set size used in kilobytes.
        network_in:
          type: integer
          description: Total received network traffic in bytes.
        network_out:
          type: integer
          description: Total transmitted network traffic in bytes.
      description: |
        Resources used by a process. This information is recorded as part of the metrics for a scraper run.

        The names of metrics are all copied from the structure returned by `getrusage(2)` (with the exception of `wall_time`)
    Event:
      required:
        - id
        - time
        - type
        - data
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        time:
          type: string
          description: Date and time of event
          # TODO: Fix time format
          format: date-time
      discriminator:
        propertyName: type
    StartEvent:
      description: Signals the start of a stage
      allOf:
        - $ref: "#/components/schemas/Event"
        - type: object
          properties:
            data:
              type: object
              properties:
                stage:
                  $ref: "#/components/schemas/Stage"
    FinishEvent:
      description: Signals the end of a stage
      allOf:
        - $ref: "#/components/schemas/Event"
        - type: object
          properties:
            data:
              type: object
              properties:
                stage:
                  $ref: "#/components/schemas/Stage"
    LastEvent:
      description: Signals the completion of the whole run
      allOf:
        - $ref: "#/components/schemas/Event"
    LogEvent:
      description: Console output event (from run)
      allOf:
        - $ref: "#/components/schemas/Event"
        - type: object
          properties:
            data:
              type: object
              properties:
                stage:
                  $ref: "#/components/schemas/Stage"
                stream:
                  type: string
                  description: |
                    Source of the message - standard output and standard error come from your code. In exceptional circumstances you might see a message from "internal error".
                  enum:
                    - stdout
                    - stderr
                    - interr
                text:
                  type: string
                  description: Console message
  securitySchemes:
    run_token:
      type: http
      scheme: bearer
