apiVersion: kubedb.com/v1alpha1
kind: Redis
metadata:
  name: redis
  namespace: yinyo-system
spec:
  version: "5.0.3-v1"
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  # TODO: Change this "DoNotTerminate" for production use
  terminationPolicy: WipeOut
  podTemplate:
    spec:
      args:
        - "--requirepass $(REDIS_PASSWORD)"
      env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis
              key: password
