apiVersion: v1
kind: ServiceAccount
metadata:
  name: clay-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clay-server
# TODO: Give it more finely tuned permissions
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: clay-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clay-server
  labels:
    app: clay-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clay-server
  template:
    metadata:
      labels:
        app: clay-server
    spec:
      serviceAccountName: clay-server
      containers:
      - name: clay-server
        image: openaustralia/clay-server
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: clay-server
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: clay-server
