apiVersion: apps/v1
kind: Deployment
metadata:
  name: clay-server
  labels:
    app: clay-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clay-server
  template:
    metadata:
      labels:
        app: clay-server
    spec:
      containers:
      - name: clay-server
        image: openaustralia/clay-server
        # Doing this so that we use the local image while we're developing
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: clay-server
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: clay-server
