apiVersion: batch/v1
kind: Job
metadata:
  name: scraper
spec:
  template:
    spec:
      containers:
      - name: scraper
        image: morph-ng
        command: ["/bin/run.sh", "{{ SCRAPER_NAMESPACE }}", "{{ SCRAPER_NAME }}"]
        # Doing this so that we use the local image while we're developing
        imagePullPolicy: Never
      restartPolicy: Never
