apiVersion: batch/v1
kind: Job
metadata:
  name: {{ SCRAPER_NAME }}
spec:
  backoffLimit: 0
  # Let this run for a maximum of 24 hours
  activeDeadlineSeconds: 86400
  template:
    spec:
      containers:
      - name: {{ SCRAPER_NAME }}
        image: clay
        command: ["/bin/run.sh", "{{ SCRAPER_NAME }}", "{{ SCRAPER_OUTPUT }}"]
        # Doing this so that we use the local image while we're developing
        imagePullPolicy: Never
        env:
          - name: CLAY_RUN_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ SCRAPER_NAME }}
                key: run_token
      restartPolicy: Never
