apiVersion: batch/v1
kind: Job
metadata:
  namespace: clay-{{ SCRAPER_NAMESPACE }}
  name: {{ SCRAPER_NAME }}
spec:
  template:
    spec:
      containers:
      - name: {{ SCRAPER_NAME }}
        image: morph-ng
        command: ["/bin/run.sh", "{{ SCRAPER_NAMESPACE }}", "{{ SCRAPER_NAME }}"]
        # Doing this so that we use the local image while we're developing
        imagePullPolicy: Never
      restartPolicy: Never
