apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-server
data:
  store_host: "{{ .Values.store.host }}"
  store_bucket: "{{ .Values.store.bucket }}"
  redis_host: "{{ .Values.redis.host }}"
  authentication_url: {{ .Values.authenticationURL }}
  usage_url: {{ .Values.usageURL }}
