apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-server
data:
  {{- if .Values.authenticationURL }}
  authentication_url: {{ .Values.authenticationURL }}
  {{ end }}
  {{- if .Values.usageURL }}
  usage_url: {{ .Values.usageURL }}
  {{ end }}
  run_docker_image: {{ .Values.runner.image }}
