apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-server
data:
  store_host: "{{ .Values.store.host }}"
  store_bucket: "{{ .Values.store.bucket }}"
  redis_host: "{{ .Values.redis.host }}"
  {{- if .Values.authenticationURL }}
  authentication_url: {{ .Values.authenticationURL }}
  {{ end }}
  {{- if .Values.usageURL }}
  usage_url: {{ .Values.usageURL }}
  {{ end }}
  run_docker_image: {{ .Values.runImage }}
