apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-server
  labels:
    app: {{ .Release.Name }}-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-server
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-server
      annotations:
        # Force an upgrade if the configmap is changed
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ .Release.Name }}-server
      containers:
        - name: {{ .Release.Name }}-server
          image: {{ .Values.server.image }}
          ports:
            - containerPort: 8080
          env:
            - name: STORE_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-server-store
                  key: host
            - name: STORE_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-server-store
                  key: bucket
            - name: STORE_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-server-store
                  key: access_key
            - name: STORE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-server-store
                  key: secret_key
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-server-redis
                  key: host
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-server-redis
                  key: password
            - name: REDIS_TLS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-server-redis
                  key: tls
            - name: RUN_DOCKER_IMAGE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-server
                  key: run_docker_image
            {{- if .Values.authenticationURL }}
            - name: AUTHENTICATION_URL
              valueFrom:
                configMapKeyRef:
                  name: yinyo-server
                  key: authentication_url
            {{ end }}
            {{- if .Values.usageURL }}
            - name: USAGE_URL
              valueFrom:
                configMapKeyRef:
                  name: yinyo-server
                  key: usage_url
            {{ end }}
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
