apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-server
  labels:
    app: {{ .Release.Name }}-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-server
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-server
    spec:
      serviceAccountName: {{ .Release.Name }}-server
      containers:
        - name: {{ .Release.Name }}-server
          image: {{ .Values.image }}
          ports:
            - containerPort: 8080
          env:
            - name: STORE_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-server
                  key: store_host
            - name: STORE_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-server
                  key: store_bucket
            - name: STORE_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-server
                  key: store_access_key
            - name: STORE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-server
                  key: store_secret_key
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: password
            # Uncomment the lines below to enable talking to an external authentication server
            # - name: AUTHENTICATION_URL
            #   valueFrom:
            #     configMapKeyRef:
            #       name: yinyo-server
            #       key: authentication_url
            # - name: USAGE_URL
            #   valueFrom:
            #     configMapKeyRef:
            #       name: yinyo-server
            #       key: usage_url
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
