apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-server
  namespace: {{ .Release.Name }}-runs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-server
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-server
    namespace: default
