apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-server
type: Opaque
data:
  store_access_key: {{ .Values.store.accessKey | b64enc }}
  store_secret_key: {{ .Values.store.secretKey | b64enc }}
  redis_password: {{ .Values.redis.password | b64enc }}
