apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-server
type: Opaque
data:
  store_access_key: {{ required "store.accessKey is required" .Values.store.accessKey | b64enc }}
  store_secret_key: {{ required "store.secretKey is required" .Values.store.secretKey | b64enc }}
  redis_password: {{ required "redis.password is required" .Values.redis.password | b64enc }}
