name: Release
on: [release]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - name: Checkout code
        uses: actions/checkout@v1
      - name: build
        run: |
          export GO111MODULE=on
          mkdir bin/
          #GOOS=windows GOARCH=amd64 go build -o bin ./...
          GOOS=linux   GOARCH=amd64 go build -o bin ./...
      - name: Go Release Binary
        uses: Shopify/upload-to-release@1.0.0
        with:
          name: yinyo
          path: bin/yinyo
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          #content-type: text/plain 
